[versions]
# Core Kotlin
kotlin = "2.3.0"

# Coroutines & Serialization & Datetime
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1"

# Compose Multiplatform
composeMultiplatform = "1.10.0"
composeHotReload = "1.0.0"

# Androidx Core
androidx-lifecycle = "2.9.6"

# Testing
junit = "4.13.2"

# Navigation
androidx-navigation = "2.9.1"

# Material Design
material3-adaptive = "1.2.0"
materialIconsExtended = "1.7.3"
material3WindowSizeClass = "1.9.0"

# DataStore
datastore = "1.2.0"

# Image Loading
coil3 = "3.3.0"

# Dependency Injection
koin = "4.1.1"

# Logging
kermit = "2.0.8"

# File
filekit = "0.12.0"

# parse for toml
akuleshov7 = "0.7.1"

# Semantic version
github-z4kn4fein = "3.0.0"

# Theme Changer
jsystemthemedetector = "3.6"

# Crash Report
sentry = "8.31.0"


[libraries]
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }

# Androidx Core
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# Kotlinx
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Material 3 Adaptive
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3WindowSizeClass" }
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
material3-adaptive-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3WindowSizeClass" }
material3-window-size-class1 = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
material3-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3-adaptive" }
material3-adaptive-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "material3-adaptive" }

# Navigation
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

# DataStore
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }

# Dependency Injection (Koin)
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

# Logging (Kermit)
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# Image Loading (Coil3)
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }

# File
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

# parse for toml
akuleshov7-ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "akuleshov7" }

# Semantic version
github-z4kn4fein-semver = { module = "io.github.z4kn4fein:semver", version.ref = "github-z4kn4fein" }

# Theme Detector
jsystemthemedetector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "jsystemthemedetector" }

# Crash Report
sentry = { module = "io.sentry:sentry", version.ref = "sentry" }


[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }