name: Build Desktop Distributions

on:
  push:
    tags:
      - 'v*' # Runs on version tags like v1.0.0

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macOS ARM (Apple Silicon)
          - os: macos-latest
            format: macos-arm
            gradle_task: packageReleaseDistributionForCurrentOS

          # macOS Intel (x64)
          - os: macos-13
            format: macos-intel
            gradle_task: packageReleaseDistributionForCurrentOS

          # Windows
          - os: windows-latest
            format: windows
            gradle_task: packageReleaseDistributionForCurrentOS

          # Linux
          - os: ubuntu-latest
            format: linux
            gradle_task: packageReleaseDistributionForCurrentOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build native packages
        run: ./gradlew ${{ matrix.gradle_task }} packageUberJarForCurrentOS --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.format }}
          path: |
            composeApp/build/compose/binaries/**/dmg/*
            composeApp/build/compose/binaries/**/deb/*
            composeApp/build/compose/binaries/**/msi/*
  #            composeApp/build/compose/binaries/**/pkg/*
  #            composeApp/build/compose/jars/*.jar
  #            composeApp/build/compose/binaries/**/app/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded files
        run: ls -R ./artifacts

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/build-macos-arm/**/*.dmg
            artifacts/build-macos-intel/**/*.dmg
            artifacts/build-macos-arm/**/*.pkg
            artifacts/build-macos-intel/**/*.pkg
            artifacts/build-windows/**/*.msi
            artifacts/build-windows/**/*.exe
            artifacts/build-windows/**/*.jar
            artifacts/build-linux/**/*.deb
            artifacts/build-linux/**/*.rpm
            artifacts/build-linux/**/*.jar
          draft: true
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
